Drv = "postgres"
Dsn = "host=127.0.0.1 port=35432 dbname=tpt user=tpt password=extreme sslmode=disable"
ControlListen="127.0.0.1:8124"

[listen]
	[listen.auth]
		Addr=":1812"
	[listen.acct]
		Addr=":1813"