Drv = "postgres"
Dsn = "host=127.0.0.1 dbname=tpt_models_test user=tpt password=extreme sslmode=disable"
ControlListen="127.0.0.1:8124"

[listen]
	[listen.auth]
		Addr="127.0.0.1:1812"
		Secret="secret"
		CIDR=["127.0.0.1/32"]
	[listen.acct]
		Addr="127.0.0.1:1813"
		Secret="secret"
		CIDR=["127.0.0.1/32"]